# services:
#   web:
#     build: .
#     command: gunicorn --bind 0.0.0.0:8000 portfolio_project.wsgi:application
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_DB: portfolio_db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 1234
#     ports:
#       - "5432:5432"

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 portfoilo_project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
# akankhya -1234 superuser
