# services:
#   web:
#     build: .
#     command: gunicorn --bind 0.0.0.0:8000 portfolio_project.wsgi:application
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_DB: portfolio_db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 1234
#     ports:
#       - "5432:5432"

# services:
#   web:
#     build: .s
#     command: gunicorn --bind 0.0.0.0:8000 portfoilo_project.wsgi:application
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_DB: portfolio_db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 1234
#     ports:
#       - "5432:5432"
# akankhya -1234 superuser





# version: "3.9"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 portfoilo_project.wsgi:application --env DJANGO_SETTINGS_MODULE=portfoilo_project.settings.prod"
    # command: gunicorn --bind 0.0.0.0:8000 portfoilo_project.wsgi:application --env DJANGO_SETTINGS_MODULE=portfoilo_project.settings.prod
    

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_ENV: production
      # In prod you set secrets in environment, NOT in .env file

  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: portfolio_db
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}




# web:
#   build: .
#   command: >
#     sh -c "python manage.py migrate &&
#            gunicorn --bind 0.0.0.0:8000 portfolio_project.wsgi:application --env DJANGO_SETTINGS_MODULE=portfolio_project.settings.prod"
#   volumes:
#     - .:/app
#   ports:
#     - "8000:8000"
#   depends_on:
#     - db
#   environment:
#     DJANGO_ENV: production
